/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yxxkishjqjsoxcjlqdrk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4eGtpc2hqcWpzb3hjamxxZHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1MzQ3NjMsImV4cCI6MjA4MDExMDc2M30.Ls-LcVQtLlyhgRXwBWe-UwmXz2rGFLzBvAtJEP4l-S4"